// <auto-generated />
namespace SaveEmployee.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class integreted001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(integreted001));
        
        string IMigrationMetadata.Id
        {
            get { return "201605080955065_integreted0.0.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
